<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H50J06T" failures="1" tests="2" name="Validating User Logout" time="25.409" errors="0" timestamp="2021-04-28T09:04:52 ICT">
  <testcase classname="TPOS.LOGIN.LogoutPage" name="loginsuccessful" time="8.964"/>
  <testcase classname="TPOS.LOGIN.LogoutPage" name="LogOutHomepage" time="10.223">
    <failure type="java.lang.AssertionError" message="expected [https://tmt30.tpos.vn/#/app/login] but found [https://tmt30.tpos.vn/#/app/dashboard]">
      <![CDATA[java.lang.AssertionError: expected [https://tmt30.tpos.vn/#/app/login] but found [https://tmt30.tpos.vn/#/app/dashboard]
at TPOS.LOGIN.LogoutPage.LogOutHomepage(LogoutPage.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LogOutHomepage -->
</testsuite> <!-- Validating User Logout -->
