<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H50J06T" failures="1" tests="2" name="Validating User Logout" time="26.696" errors="0" timestamp="2021-06-02T18:16:38 ICT">
  <testcase classname="TPOS.LOGIN.LogoutPage" name="LoginTPOS" time="9.324"/>
  <testcase classname="TPOS.LOGIN.LogoutPage" name="LogOutTPOS" time="10.27">
    <failure type="java.lang.AssertionError" message="expected [https://tmt30.tpos.vn/#/app/login] but found [https://tmt30.tpos.vn/#/app/dashboard]">
      <![CDATA[java.lang.AssertionError: expected [https://tmt30.tpos.vn/#/app/login] but found [https://tmt30.tpos.vn/#/app/dashboard]
at TPOS.LOGIN.LogoutPage.LogOutTPOS(LogoutPage.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LogOutTPOS -->
</testsuite> <!-- Validating User Logout -->
